from __future__ import annotations

from typing import Optional, overload

__all__ = [
    "DataSet",
    "read_file",
    "read_bytes",
    "Tag",
    "VR",
    "keyword_to_tag_vr",
    "tag_to_keyword",
]


class DataSet:
    @property
    def path(self) -> str: ...


class Tag:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, group: int, element: int, /) -> None: ...

    @overload
    def __init__(self, keyword: str, /) -> None: ...

    @staticmethod
    def from_value(value: int, /) -> Tag: ...

    @property
    def group(self) -> int: ...

    @property
    def element(self) -> int: ...

    @property
    def value(self) -> int: ...

    def is_private(self) -> bool: ...

    def __int__(self) -> int: ...

    def __bool__(self) -> bool: ...


class VR:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, value: int, /) -> None: ...

    @staticmethod
    def from_string(value: str, /) -> VR: ...

    @staticmethod
    def from_chars(first: str, second: str, /) -> VR: ...

    @property
    def value(self) -> int: ...

    @property
    def is_known(self) -> bool: ...

    def is_string(self) -> bool: ...

    def is_binary(self) -> bool: ...

    def is_sequence(self) -> bool: ...

    def padding_byte(self) -> int: ...

    def uses_explicit_32bit_vl(self) -> bool: ...

    def fixed_length(self) -> int: ...

    def str(self) -> str: ...

    def first(self) -> str: ...

    def second(self) -> str: ...


def keyword_to_tag_vr(keyword: str, /) -> Optional[tuple[Tag, VR]]: ...


def read_file(path: str, /) -> DataSet: ...


def read_bytes(data: bytes | bytearray | memoryview, name: str = "<memory>", /) -> DataSet: ...


@overload
def tag_to_keyword(tag: Tag, /) -> Optional[str]: ...

@overload
def tag_to_keyword(tag_value: int, /) -> Optional[str]: ...
