from __future__ import annotations

from typing import Optional, overload

DICOM_STANDARD_VERSION: str
DICOMSDL_VERSION: str
__version__: str

__all__ = [
    "DataSet",
    "Tag",
    "Uid",
    "VR",
    "read_file",
    "read_bytes",
    "keyword_to_tag_vr",
    "tag_to_keyword",
    "lookup_uid",
    "uid_from_value",
    "uid_from_keyword",
]


class DataSet:
    @property
    def path(self) -> str: ...


class Tag:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, group: int, element: int, /) -> None: ...

    @overload
    def __init__(self, keyword: str, /) -> None: ...

    @staticmethod
    def from_value(value: int, /) -> Tag: ...

    @property
    def group(self) -> int: ...

    @property
    def element(self) -> int: ...

    @property
    def value(self) -> int: ...

    def is_private(self) -> bool: ...

    def __int__(self) -> int: ...

    def __bool__(self) -> bool: ...


class VR:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, value: int, /) -> None: ...

    @staticmethod
    def from_string(value: str, /) -> VR: ...

    @staticmethod
    def from_chars(first: str, second: str, /) -> VR: ...

    @property
    def value(self) -> int: ...

    @property
    def is_known(self) -> bool: ...

    def is_string(self) -> bool: ...

    def is_binary(self) -> bool: ...

    def is_sequence(self) -> bool: ...

    def is_pixel_sequence(self) -> bool: ...

    def padding_byte(self) -> int: ...

    def uses_explicit_32bit_vl(self) -> bool: ...

    def fixed_length(self) -> int: ...

    def str(self) -> str: ...

    def first(self) -> str: ...

    def second(self) -> str: ...


def keyword_to_tag_vr(keyword: str, /) -> Optional[tuple[Tag, VR]]: ...

class Uid:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, text: str, /) -> None: ...

    @staticmethod
    def lookup(text: str, /) -> Optional[Uid]: ...

    @staticmethod
    def from_value(value: str, /) -> Uid: ...

    @staticmethod
    def from_keyword(keyword: str, /) -> Uid: ...

    @property
    def value(self) -> str: ...

    @property
    def keyword(self) -> Optional[str]: ...

    @property
    def name(self) -> str: ...

    @property
    def type(self) -> str: ...

    @property
    def raw_index(self) -> int: ...

    @property
    def is_valid(self) -> bool: ...

    def __bool__(self) -> bool: ...


def read_file(path: str, /) -> DataSet: ...


def read_bytes(data: bytes | bytearray | memoryview, name: str = "<memory>", /) -> DataSet: ...


@overload
def tag_to_keyword(tag: Tag, /) -> Optional[str]: ...

@overload
def tag_to_keyword(tag_value: int, /) -> Optional[str]: ...

def lookup_uid(text: str, /) -> Optional[Uid]: ...

def uid_from_value(value: str, /) -> Uid: ...

def uid_from_keyword(keyword: str, /) -> Uid: ...
