@echo off
setlocal

set "ROOT_DIR=%~dp0"

if not defined PYTHON_BIN set "PYTHON_BIN=python"
if not defined DICOMSDL_WINDOWS_TOOLCHAIN set "DICOMSDL_WINDOWS_TOOLCHAIN=msvc"
if not defined BUILD_DIR set "BUILD_DIR=%ROOT_DIR%build-wheel-static"
if not defined WHEEL_DIR set "WHEEL_DIR=%ROOT_DIR%dist-static"
if not defined RESET_CMAKE_CACHE set "RESET_CMAKE_CACHE=1"
if not defined BUILD_TESTING set "BUILD_TESTING=OFF"
if not defined DICOM_BUILD_EXAMPLES set "DICOM_BUILD_EXAMPLES=OFF"
if not defined RUN_TESTS set "RUN_TESTS=0"
if not defined BUILD_WHEEL set "BUILD_WHEEL=1"

if not defined DICOMSDL_PIXEL_DEFAULT_MODE set "DICOMSDL_PIXEL_DEFAULT_MODE=none"
if not defined DICOMSDL_PIXEL_JPEG_MODE set "DICOMSDL_PIXEL_JPEG_MODE=builtin"
if not defined DICOMSDL_PIXEL_JPEGLS_MODE set "DICOMSDL_PIXEL_JPEGLS_MODE=builtin"
if not defined DICOMSDL_PIXEL_JPEG2K_MODE set "DICOMSDL_PIXEL_JPEG2K_MODE=builtin"
if not defined DICOMSDL_PIXEL_HTJ2K_MODE set "DICOMSDL_PIXEL_HTJ2K_MODE=builtin"
if not defined DICOMSDL_PIXEL_JPEGXL_MODE set "DICOMSDL_PIXEL_JPEGXL_MODE=builtin"

if not defined CMAKE_EXTRA_ARGS set "CMAKE_EXTRA_ARGS=-DDICOM_BUILD_PYTHON=OFF -DDICOMSDL_ENABLE_JPEGXL=ON -DDICOMSDL_PIXEL_OPENJPEG_PLUGIN=OFF -DDICOMSDL_PIXEL_JPEG_PLUGIN=OFF -DDICOMSDL_PIXEL_JPEGLS_PLUGIN=OFF -DDICOMSDL_PIXEL_HTJ2K_PLUGIN=OFF -DDICOMSDL_PIXEL_JPEGXL_PLUGIN=OFF -DDICOMSDL_PIXEL_RLE_STATIC_PLUGIN=ON -DDICOMSDL_PIXEL_OPENJPEG_STATIC_PLUGIN=ON -DDICOMSDL_PIXEL_JPEG_STATIC_PLUGIN=ON -DDICOMSDL_PIXEL_JPEGLS_STATIC_PLUGIN=ON -DDICOMSDL_PIXEL_HTJ2K_STATIC_PLUGIN=ON -DDICOMSDL_PIXEL_JPEGXL_STATIC_PLUGIN=ON"
if not defined DICOMSDL_CMAKE_ARGS set "DICOMSDL_CMAKE_ARGS=-DDICOMSDL_ENABLE_JPEGXL=ON -DDICOMSDL_PIXEL_OPENJPEG_PLUGIN=OFF -DDICOMSDL_PIXEL_JPEG_PLUGIN=OFF -DDICOMSDL_PIXEL_JPEGLS_PLUGIN=OFF -DDICOMSDL_PIXEL_HTJ2K_PLUGIN=OFF -DDICOMSDL_PIXEL_JPEGXL_PLUGIN=OFF -DDICOMSDL_PIXEL_RLE_STATIC_PLUGIN=ON -DDICOMSDL_PIXEL_OPENJPEG_STATIC_PLUGIN=ON -DDICOMSDL_PIXEL_JPEG_STATIC_PLUGIN=ON -DDICOMSDL_PIXEL_JPEGLS_STATIC_PLUGIN=ON -DDICOMSDL_PIXEL_HTJ2K_STATIC_PLUGIN=ON -DDICOMSDL_PIXEL_JPEGXL_STATIC_PLUGIN=ON"

call "%ROOT_DIR%build.bat" %*
set "EXIT_CODE=%ERRORLEVEL%"
endlocal & exit /b %EXIT_CODE%
