#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${ROOT_DIR}"

: "${PYTHON_BIN:=python3}"
: "${BUILD_DIR:=${ROOT_DIR}/build-wheel-shared}"
: "${WHEEL_DIR:=${ROOT_DIR}/dist-shared}"
: "${RESET_CMAKE_CACHE:=1}"
: "${BUILD_TESTING:=OFF}"
: "${DICOM_BUILD_EXAMPLES:=OFF}"
: "${RUN_TESTS:=0}"
: "${BUILD_WHEEL:=1}"

: "${DICOMSDL_CODEC_DEFAULT_MODE:=none}"
: "${DICOMSDL_CODEC_JPEG_MODE:=shared}"
: "${DICOMSDL_CODEC_JPEGLS_MODE:=shared}"
: "${DICOMSDL_CODEC_JPEG2K_MODE:=shared}"
: "${DICOMSDL_CODEC_HTJ2K_MODE:=shared}"
: "${DICOMSDL_CODEC_JPEGXL_MODE:=shared}"

shared_args="-DDICOM_BUILD_PYTHON=OFF -DDICOMSDL_ENABLE_JPEGXL=ON -DDICOMSDL_PIXEL_RLE_STATIC_PLUGIN=OFF -DDICOMSDL_PIXEL_OPENJPEG_STATIC_PLUGIN=OFF -DDICOMSDL_PIXEL_JPEG_STATIC_PLUGIN=OFF -DDICOMSDL_PIXEL_JPEGLS_STATIC_PLUGIN=OFF -DDICOMSDL_PIXEL_HTJ2K_STATIC_PLUGIN=OFF -DDICOMSDL_PIXEL_JPEGXL_STATIC_PLUGIN=OFF -DDICOMSDL_PIXEL_OPENJPEG_PLUGIN=ON -DDICOMSDL_PIXEL_JPEG_PLUGIN=ON -DDICOMSDL_PIXEL_JPEGLS_PLUGIN=ON -DDICOMSDL_PIXEL_HTJ2K_PLUGIN=ON -DDICOMSDL_PIXEL_JPEGXL_PLUGIN=ON"
shared_wheel_args="-DDICOMSDL_ENABLE_JPEGXL=ON -DDICOMSDL_PIXEL_RLE_STATIC_PLUGIN=OFF -DDICOMSDL_PIXEL_OPENJPEG_STATIC_PLUGIN=OFF -DDICOMSDL_PIXEL_JPEG_STATIC_PLUGIN=OFF -DDICOMSDL_PIXEL_JPEGLS_STATIC_PLUGIN=OFF -DDICOMSDL_PIXEL_HTJ2K_STATIC_PLUGIN=OFF -DDICOMSDL_PIXEL_JPEGXL_STATIC_PLUGIN=OFF -DDICOMSDL_PIXEL_OPENJPEG_PLUGIN=ON -DDICOMSDL_PIXEL_JPEG_PLUGIN=ON -DDICOMSDL_PIXEL_JPEGLS_PLUGIN=ON -DDICOMSDL_PIXEL_HTJ2K_PLUGIN=ON -DDICOMSDL_PIXEL_JPEGXL_PLUGIN=ON"

: "${CMAKE_EXTRA_ARGS:=${shared_args}}"
: "${DICOMSDL_CMAKE_ARGS:=${shared_wheel_args}}"

export PYTHON_BIN
export BUILD_DIR
export WHEEL_DIR
export RESET_CMAKE_CACHE
export BUILD_TESTING
export DICOM_BUILD_EXAMPLES
export RUN_TESTS
export BUILD_WHEEL
export DICOMSDL_CODEC_DEFAULT_MODE
export DICOMSDL_CODEC_JPEG_MODE
export DICOMSDL_CODEC_JPEGLS_MODE
export DICOMSDL_CODEC_JPEG2K_MODE
export DICOMSDL_CODEC_HTJ2K_MODE
export DICOMSDL_CODEC_JPEGXL_MODE
export CMAKE_EXTRA_ARGS
export DICOMSDL_CMAKE_ARGS

exec "${ROOT_DIR}/build.sh" "$@"
