from collections.abc import Callable, Sequence as _Sequence
import enum
from typing import Literal, TypeAlias, overload

from dicomsdl._image import _dicomfile_to_pil_image as to_pil_image


DICOM_STANDARD_VERSION: str = ...

DICOMSDL_VERSION: str = ...

UID_PREFIX: str = ...

IMPLEMENTATION_CLASS_UID: str = ...

IMPLEMENTATION_VERSION_NAME: str = ...

def log_info(arg: str, /) -> None: ...

def log_warn(arg: str, /) -> None: ...

def log_error(arg: str, /) -> None: ...

class LogLevel(enum.Enum):
    Info = 0

    Warning = 1

    Error = 2

class Reporter:
    pass

class StderrReporter(Reporter):
    def __init__(self) -> None: ...

class FileReporter(Reporter):
    def __init__(self, path: object) -> None: ...

class BufferingReporter(Reporter):
    def __init__(self, max_messages: int = ...) -> None: ...

    def take_messages(self, include_level: bool = ...) -> list[str]: ...

    def for_each(self, fn: Callable) -> None: ...

def set_default_reporter(reporter: Reporter | None) -> None: ...

def set_thread_reporter(reporter: Reporter | None) -> None: ...

def set_log_level(level: LogLevel) -> None: ...

class PersonNameGroup:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, components: _Sequence[str]) -> None: ...

    @property
    def components(self) -> list[str]: ...

    @components.setter
    def components(self, arg: _Sequence[str], /) -> None: ...

    def component(self, index: int) -> str: ...

    def empty(self) -> bool: ...

    def to_dicom_string(self) -> str: ...

    @property
    def family_name(self) -> str: ...

    @family_name.setter
    def family_name(self, arg: str, /) -> None: ...

    @property
    def given_name(self) -> str: ...

    @given_name.setter
    def given_name(self, arg: str, /) -> None: ...

    @property
    def middle_name(self) -> str: ...

    @middle_name.setter
    def middle_name(self, arg: str, /) -> None: ...

    @property
    def name_prefix(self) -> str: ...

    @name_prefix.setter
    def name_prefix(self, arg: str, /) -> None: ...

    @property
    def name_suffix(self) -> str: ...

    @name_suffix.setter
    def name_suffix(self, arg: str, /) -> None: ...

    def __repr__(self) -> str: ...

class PersonName:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, *, alphabetic: object | None = ..., ideographic: object | None = ..., phonetic: object | None = ...) -> None: ...

    @property
    def alphabetic(self) -> object: ...

    @alphabetic.setter
    def alphabetic(self, arg: object, /) -> None: ...

    @property
    def ideographic(self) -> object: ...

    @ideographic.setter
    def ideographic(self, arg: object, /) -> None: ...

    @property
    def phonetic(self) -> object: ...

    @phonetic.setter
    def phonetic(self, arg: object, /) -> None: ...

    def empty(self) -> bool: ...

    def to_dicom_string(self) -> str: ...

    def __repr__(self) -> str: ...

class DataElement:
    @property
    def tag(self) -> Tag: ...

    @property
    def vr(self) -> VR: ...

    @property
    def length(self) -> int: ...

    @property
    def offset(self) -> int: ...

    @property
    def vm(self) -> int: ...

    @property
    def value(self) -> object: ...

    @value.setter
    def value(self, arg: object, /) -> None: ...

    def __bool__(self) -> bool: ...

    def is_present(self) -> bool: ...

    def is_missing(self) -> bool: ...

    @property
    def is_sequence(self) -> bool: ...

    @property
    def is_pixel_sequence(self) -> bool: ...

    @property
    def sequence(self) -> Sequence: ...

    @property
    def pixel_sequence(self) -> PixelSequence: ...

    def set_value(self, value: object) -> bool: ...

    def from_double(self, value: float) -> bool: ...

    def from_double_vector(self, values: _Sequence[float]) -> bool: ...

    def from_tag(self, value: Tag) -> bool: ...

    def from_tag_vector(self, values: _Sequence[Tag]) -> bool: ...

    def from_string_view(self, value: str) -> bool: ...

    def from_string_views(self, values: _Sequence[str]) -> bool: ...

    def from_utf8_view(self, value: str, *, errors: object = ..., return_replaced: bool = ...) -> object: ...

    def from_utf8_views(self, values: _Sequence[str], *, errors: object = ..., return_replaced: bool = ...) -> object: ...

    def from_person_name(self, value: PersonName, *, errors: object = ..., return_replaced: bool = ...) -> object: ...

    def from_person_names(self, values: _Sequence[PersonName], *, errors: object = ..., return_replaced: bool = ...) -> object: ...

    def to_uid_string(self) -> object: ...

    def to_string_view(self) -> object: ...

    def to_string_views(self) -> object: ...

    def to_utf8_string(self, *, errors: object = ..., return_replaced: bool = ...) -> object: ...

    def to_utf8_strings(self, *, errors: object = ..., return_replaced: bool = ...) -> object: ...

    def to_person_name(self, *, errors: object = ..., return_replaced: bool = ...) -> object: ...

    def to_person_names(self, *, errors: object = ..., return_replaced: bool = ...) -> object: ...

    def to_transfer_syntax_uid(self) -> object: ...

    def to_tag(self, default: object | None = ...) -> object: ...

    def to_tag_vector(self) -> object: ...

    def to_int(self, default: object | None = ...) -> object: ...

    def to_long(self, default: object | None = ...) -> object: ...

    def to_longlong(self, default: object | None = ...) -> object: ...

    def to_double(self, default: object | None = ...) -> object: ...

    def to_int_vector(self, default: object | None = ...) -> object: ...

    def to_long_vector(self, default: object | None = ...) -> object: ...

    def to_longlong_vector(self, default: object | None = ...) -> object: ...

    def to_double_vector(self, default: object | None = ...) -> object: ...

    def get_value(self) -> object: ...

    def value_span(self) -> object: ...

    def value_bytes(self) -> bytes: ...

    def __repr__(self) -> str: ...

class SequenceIterator:
    def __iter__(self) -> SequenceIterator: ...

    def __next__(self) -> DataSet: ...

class Sequence:
    def __len__(self) -> int: ...

    def __getitem__(self, index: int) -> DataSet: ...

    def __iter__(self) -> SequenceIterator: ...

    def add_dataset(self) -> DataSet: ...

    def __repr__(self) -> str: ...

class DataElementIterator:
    def __iter__(self) -> DataElementIterator: ...

    def __next__(self) -> DataElement: ...

class DataSetWalkPath:
    def __len__(self) -> int: ...

    def __bool__(self) -> bool: ...

    def contains_sequence(self, tag: object) -> bool: ...

    def to_string(self) -> str: ...

class DataSetWalkEntry(tuple[DataSetWalkPath, DataElement]):
    @property
    def path(self) -> DataSetWalkPath: ...

    @property
    def element(self) -> DataElement: ...

    def skip_sequence(self) -> None: ...

    def skip_current_dataset(self) -> None: ...

class DataSetWalkEntryIterator:
    def __iter__(self) -> DataSetWalkEntryIterator: ...

    def __next__(self) -> DataSetWalkPath | DataElement: ...

class DataSetWalkIterator:
    def __iter__(self) -> DataSetWalkIterator: ...

    def __next__(self) -> DataSetWalkEntry: ...

    def skip_sequence(self) -> None: ...

    def skip_current_dataset(self) -> None: ...

DataSetSelectionTagLike: TypeAlias = Tag | int | str

DataSetSelectionNodesLike: TypeAlias = (
    list["DataSetSelectionNodeLike"] | tuple["DataSetSelectionNodeLike", ...]
)

DataSetSelectionNodeLike: TypeAlias = (
    DataSetSelectionTagLike
    | tuple[DataSetSelectionTagLike, DataSetSelectionNodesLike]
)

class DataSetSelection:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, nodes: DataSetSelectionNodesLike, /) -> None: ...

    def __len__(self) -> int: ...

    def __bool__(self) -> bool: ...

DataSetSelectionLike: TypeAlias = DataSetSelection | DataSetSelectionNodesLike

class DataSet:
    def __setattr__(self, name, value, /): ...

    def __delattr__(self, name, /): ...

    def __init__(self) -> None: ...

    @property
    def path(self) -> str: ...

    def size(self) -> int: ...

    def add_dataelement(self, tag: object, vr: VR | None = ...) -> DataElement: ...

    def ensure_dataelement(self, tag: object, vr: VR | None = ...) -> DataElement: ...

    def ensure_loaded(self, tag: object) -> None: ...

    def remove_dataelement(self, tag: object) -> None: ...

    def dump_elements(self) -> None: ...

    def dump(self, max_print_chars: int = ..., include_offset: bool = ...) -> str: ...

    def get_dataelement(self, key: object) -> DataElement: ...

    def get_value(self, key: object, default: object | None = ...) -> object: ...

    @overload
    def set_value(self, key: object, value: object) -> bool: ...

    @overload
    def set_value(self, key: object, vr: VR, value: object) -> bool: ...

    def __getitem__(self, key: object) -> DataElement: ...

    def __contains__(self, key: object) -> bool: ...

    def __getattr__(self, name: str) -> object: ...

    def __dir__(self) -> list: ...

    def __iter__(self) -> DataElementIterator: ...

    def walk(self) -> DataSetWalkIterator: ...

class Planar(enum.Enum):
    interleaved = 0

    planar = 1

class DecodeOptions:
    def __init__(self, *, alignment: int = ..., row_stride: int = ..., frame_stride: int = ..., planar_out: Planar = Planar.interleaved, decode_mct: bool = ..., worker_threads: int = ..., codec_threads: int = ...) -> None: ...

    @property
    def alignment(self) -> int: ...

    @alignment.setter
    def alignment(self, arg: int, /) -> None: ...

    @property
    def row_stride(self) -> int: ...

    @row_stride.setter
    def row_stride(self, arg: int, /) -> None: ...

    @property
    def frame_stride(self) -> int: ...

    @frame_stride.setter
    def frame_stride(self, arg: int, /) -> None: ...

    @property
    def planar_out(self) -> Planar: ...

    @planar_out.setter
    def planar_out(self, arg: Planar, /) -> None: ...

    @property
    def decode_mct(self) -> bool: ...

    @decode_mct.setter
    def decode_mct(self, arg: bool, /) -> None: ...

    @property
    def worker_threads(self) -> int: ...

    @worker_threads.setter
    def worker_threads(self, arg: int, /) -> None: ...

    @property
    def codec_threads(self) -> int: ...

    @codec_threads.setter
    def codec_threads(self, arg: int, /) -> None: ...

    def __repr__(self) -> str: ...

class DecodePlan:
    @property
    def options(self) -> DecodeOptions: ...

    @property
    def has_pixel_data(self) -> bool: ...

    @property
    def rows(self) -> int: ...

    @property
    def cols(self) -> int: ...

    @property
    def frames(self) -> int: ...

    @property
    def samples_per_pixel(self) -> int: ...

    @property
    def bits_stored(self) -> int: ...

    @property
    def row_stride(self) -> int: ...

    @property
    def frame_stride(self) -> int: ...

    @property
    def dtype(self) -> object: ...

    @property
    def bytes_per_sample(self) -> int: ...

    def shape(self, frame: int = ...) -> tuple: ...

    def required_bytes(self, frame: int = ...) -> int: ...

    def __repr__(self) -> str: ...

class RescaleTransform:
    def __init__(self) -> None: ...

    @property
    def slope(self) -> float: ...

    @slope.setter
    def slope(self, arg: float, /) -> None: ...

    @property
    def intercept(self) -> float: ...

    @intercept.setter
    def intercept(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

class ModalityLut:
    def __init__(self) -> None: ...

    @property
    def first_mapped(self) -> int: ...

    @first_mapped.setter
    def first_mapped(self, arg: int, /) -> None: ...

    @property
    def values(self) -> list[float]: ...

    @values.setter
    def values(self, arg: _Sequence[float], /) -> None: ...

    def __repr__(self) -> str: ...

class PaletteLut:
    def __init__(self) -> None: ...

    @property
    def first_mapped(self) -> int: ...

    @first_mapped.setter
    def first_mapped(self, arg: int, /) -> None: ...

    @property
    def bits_per_entry(self) -> int: ...

    @bits_per_entry.setter
    def bits_per_entry(self, arg: int, /) -> None: ...

    @property
    def red_values(self) -> list[int]: ...

    @red_values.setter
    def red_values(self, arg: _Sequence[int], /) -> None: ...

    @property
    def green_values(self) -> list[int]: ...

    @green_values.setter
    def green_values(self, arg: _Sequence[int], /) -> None: ...

    @property
    def blue_values(self) -> list[int]: ...

    @blue_values.setter
    def blue_values(self, arg: _Sequence[int], /) -> None: ...

    @property
    def alpha_values(self) -> list[int]: ...

    @alpha_values.setter
    def alpha_values(self, arg: _Sequence[int], /) -> None: ...

    def __repr__(self) -> str: ...

class PixelPresentation(enum.Enum):
    monochrome = 0

    color = 1

    mixed = 2

    true_color = 3

    color_range = 4

    color_ref = 5

class SupplementalPaletteInfo:
    def __init__(self) -> None: ...

    @property
    def pixel_presentation(self) -> PixelPresentation: ...

    @pixel_presentation.setter
    def pixel_presentation(self, arg: PixelPresentation, /) -> None: ...

    @property
    def palette(self) -> PaletteLut: ...

    @palette.setter
    def palette(self, arg: PaletteLut, /) -> None: ...

    @property
    def has_stored_value_range(self) -> bool: ...

    @has_stored_value_range.setter
    def has_stored_value_range(self, arg: bool, /) -> None: ...

    @property
    def minimum_stored_value_mapped(self) -> float: ...

    @minimum_stored_value_mapped.setter
    def minimum_stored_value_mapped(self, arg: float, /) -> None: ...

    @property
    def maximum_stored_value_mapped(self) -> float: ...

    @maximum_stored_value_mapped.setter
    def maximum_stored_value_mapped(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

class EnhancedPaletteDataPathAssignmentInfo:
    def __init__(self) -> None: ...

    @property
    def data_type(self) -> str: ...

    @data_type.setter
    def data_type(self, arg: str, /) -> None: ...

    @property
    def data_path_assignment(self) -> str: ...

    @data_path_assignment.setter
    def data_path_assignment(self, arg: str, /) -> None: ...

    @property
    def has_bits_mapped_to_color_lookup_table(self) -> bool: ...

    @has_bits_mapped_to_color_lookup_table.setter
    def has_bits_mapped_to_color_lookup_table(self, arg: bool, /) -> None: ...

    @property
    def bits_mapped_to_color_lookup_table(self) -> int: ...

    @bits_mapped_to_color_lookup_table.setter
    def bits_mapped_to_color_lookup_table(self, arg: int, /) -> None: ...

class EnhancedBlendingLutInfo:
    def __init__(self) -> None: ...

    @property
    def transfer_function(self) -> str: ...

    @transfer_function.setter
    def transfer_function(self, arg: str, /) -> None: ...

    @property
    def has_weight_constant(self) -> bool: ...

    @has_weight_constant.setter
    def has_weight_constant(self, arg: bool, /) -> None: ...

    @property
    def weight_constant(self) -> float: ...

    @weight_constant.setter
    def weight_constant(self, arg: float, /) -> None: ...

    @property
    def bits_per_entry(self) -> int: ...

    @bits_per_entry.setter
    def bits_per_entry(self, arg: int, /) -> None: ...

    @property
    def values(self) -> list[int]: ...

    @values.setter
    def values(self, arg: _Sequence[int], /) -> None: ...

    def __repr__(self) -> str: ...

class EnhancedPaletteItemInfo:
    def __init__(self) -> None: ...

    @property
    def data_path_id(self) -> str: ...

    @data_path_id.setter
    def data_path_id(self, arg: str, /) -> None: ...

    @property
    def rgb_lut_transfer_function(self) -> str: ...

    @rgb_lut_transfer_function.setter
    def rgb_lut_transfer_function(self, arg: str, /) -> None: ...

    @property
    def alpha_lut_transfer_function(self) -> str: ...

    @alpha_lut_transfer_function.setter
    def alpha_lut_transfer_function(self, arg: str, /) -> None: ...

    @property
    def palette(self) -> PaletteLut: ...

    @palette.setter
    def palette(self, arg: PaletteLut, /) -> None: ...

class EnhancedPaletteInfo:
    def __init__(self) -> None: ...

    @property
    def pixel_presentation(self) -> PixelPresentation: ...

    @pixel_presentation.setter
    def pixel_presentation(self, arg: PixelPresentation, /) -> None: ...

    @property
    def data_frame_assignments(self) -> list[EnhancedPaletteDataPathAssignmentInfo]: ...

    @data_frame_assignments.setter
    def data_frame_assignments(self, arg: _Sequence[EnhancedPaletteDataPathAssignmentInfo], /) -> None: ...

    @property
    def has_blending_lut_1(self) -> bool: ...

    @has_blending_lut_1.setter
    def has_blending_lut_1(self, arg: bool, /) -> None: ...

    @property
    def blending_lut_1(self) -> EnhancedBlendingLutInfo: ...

    @blending_lut_1.setter
    def blending_lut_1(self, arg: EnhancedBlendingLutInfo, /) -> None: ...

    @property
    def has_blending_lut_2(self) -> bool: ...

    @has_blending_lut_2.setter
    def has_blending_lut_2(self, arg: bool, /) -> None: ...

    @property
    def blending_lut_2(self) -> EnhancedBlendingLutInfo: ...

    @blending_lut_2.setter
    def blending_lut_2(self, arg: EnhancedBlendingLutInfo, /) -> None: ...

    @property
    def palette_items(self) -> list[EnhancedPaletteItemInfo]: ...

    @palette_items.setter
    def palette_items(self, arg: _Sequence[EnhancedPaletteItemInfo], /) -> None: ...

    @property
    def has_icc_profile(self) -> bool: ...

    @has_icc_profile.setter
    def has_icc_profile(self, arg: bool, /) -> None: ...

    @property
    def color_space(self) -> str: ...

    @color_space.setter
    def color_space(self, arg: str, /) -> None: ...

    def __repr__(self) -> str: ...

class VoiLut:
    def __init__(self) -> None: ...

    @property
    def first_mapped(self) -> int: ...

    @first_mapped.setter
    def first_mapped(self, arg: int, /) -> None: ...

    @property
    def bits_per_entry(self) -> int: ...

    @bits_per_entry.setter
    def bits_per_entry(self, arg: int, /) -> None: ...

    @property
    def values(self) -> list[int]: ...

    @values.setter
    def values(self, arg: _Sequence[int], /) -> None: ...

    def __repr__(self) -> str: ...

class VoiLutFunction(enum.Enum):
    linear = 0

    linear_exact = 1

    sigmoid = 2

class WindowTransform:
    def __init__(self) -> None: ...

    @property
    def center(self) -> float: ...

    @center.setter
    def center(self, arg: float, /) -> None: ...

    @property
    def width(self) -> float: ...

    @width.setter
    def width(self, arg: float, /) -> None: ...

    @property
    def function(self) -> VoiLutFunction: ...

    @function.setter
    def function(self, arg: VoiLutFunction, /) -> None: ...

    def __repr__(self) -> str: ...

class EncoderContext:
    def __init__(self) -> None: ...

    def __enter__(self) -> EncoderContext: ...

    def __exit__(self, exc_type: object | None, exc_value: object | None, traceback: object | None) -> bool: ...

    @overload
    def configure(self, transfer_syntax: Uid, *, options: object | None = ...) -> None: ...

    @overload
    def configure(self, transfer_syntax: str, *, options: object | None = ...) -> None: ...

    @property
    def configured(self) -> bool: ...

    @property
    def transfer_syntax_uid(self) -> object: ...

class DicomFile:
    def __setattr__(self, name, value, /): ...

    def __delattr__(self, name, /): ...

    def __init__(self) -> None: ...

    @property
    def path(self) -> str: ...

    @property
    def transfer_syntax_uid(self) -> object: ...

    @property
    def window_transform(self) -> object: ...

    def window_transform_for_frame(self, frame_index: int) -> object: ...

    @property
    def rescale_transform(self) -> object: ...

    def rescale_transform_for_frame(self, frame_index: int) -> object: ...

    @property
    def modality_lut(self) -> object: ...

    def modality_lut_for_frame(self, frame_index: int) -> object: ...

    @property
    def pixel_presentation(self) -> object: ...

    @property
    def voi_lut(self) -> object: ...

    def voi_lut_for_frame(self, frame_index: int) -> object: ...

    @property
    def palette_lut(self) -> object: ...

    @property
    def supplemental_palette(self) -> object: ...

    @property
    def enhanced_palette(self) -> object: ...

    @property
    def has_error(self) -> bool: ...

    @property
    def error_message(self) -> object: ...

    @property
    def dataset(self) -> DataSet: ...

    def add_dataelement(self, tag: object, vr: VR | None = ...) -> DataElement: ...

    def ensure_dataelement(self, tag: object, vr: VR | None = ...) -> DataElement: ...

    def ensure_loaded(self, tag: object) -> None: ...

    def remove_dataelement(self, tag: object) -> None: ...

    def get_dataelement(self, key: object) -> DataElement: ...

    def get_value(self, key: object, default: object | None = ...) -> object: ...

    @overload
    def set_value(self, key: object, value: object) -> bool: ...

    @overload
    def set_value(self, key: object, vr: VR, value: object) -> bool: ...

    @overload
    def create_decode_plan(self) -> DecodePlan: ...

    @overload
    def create_decode_plan(self, options: DecodeOptions) -> DecodePlan: ...

    def __len__(self) -> int: ...

    def dump(self, max_print_chars: int = ..., include_offset: bool = ...) -> str: ...

    def rebuild_file_meta(self) -> None: ...

    @overload
    def set_transfer_syntax(self, transfer_syntax: Uid, *, options: object | None = ...) -> None: ...

    @overload
    def set_transfer_syntax(self, transfer_syntax: str, *, options: object | None = ...) -> None: ...

    @overload
    def set_transfer_syntax(self, transfer_syntax: Uid, *, encoder_context: EncoderContext) -> None: ...

    @overload
    def set_transfer_syntax(self, transfer_syntax: str, *, encoder_context: EncoderContext) -> None: ...

    def set_declared_specific_charset(self, specific_charset: object) -> None: ...

    def set_specific_charset(self, specific_charset: object, *, errors: object = ..., return_replaced: bool = ...) -> object: ...

    @overload
    def set_pixel_data(self, transfer_syntax: Uid, source: object, *, options: object | None = ...) -> None: ...

    @overload
    def set_pixel_data(self, transfer_syntax: str, source: object, *, options: object | None = ...) -> None: ...

    @overload
    def set_pixel_data(self, transfer_syntax: Uid, source: object, *, encoder_context: EncoderContext) -> None: ...

    @overload
    def set_pixel_data(self, transfer_syntax: str, source: object, *, encoder_context: EncoderContext) -> None: ...

    def write_file(self, path: object, *, include_preamble: bool = ..., write_file_meta: bool = ..., keep_existing_meta: bool = ...) -> None: ...

    @overload
    def write_with_transfer_syntax(self, path: object, transfer_syntax: Uid, *, options: object | None = ..., include_preamble: bool = ..., write_file_meta: bool = ..., keep_existing_meta: bool = ...) -> None: ...

    @overload
    def write_with_transfer_syntax(self, path: object, transfer_syntax: str, *, options: object | None = ..., include_preamble: bool = ..., write_file_meta: bool = ..., keep_existing_meta: bool = ...) -> None: ...

    @overload
    def write_with_transfer_syntax(self, path: object, transfer_syntax: Uid, *, encoder_context: EncoderContext, include_preamble: bool = ..., write_file_meta: bool = ..., keep_existing_meta: bool = ...) -> None: ...

    @overload
    def write_with_transfer_syntax(self, path: object, transfer_syntax: str, *, encoder_context: EncoderContext, include_preamble: bool = ..., write_file_meta: bool = ..., keep_existing_meta: bool = ...) -> None: ...

    def write_bytes(self, *, include_preamble: bool = ..., write_file_meta: bool = ..., keep_existing_meta: bool = ...) -> bytes: ...

    def __iter__(self) -> DataElementIterator: ...

    def walk(self) -> DataSetWalkIterator: ...

    def pixel_data(self, frame_index: int = ...) -> bytes: ...
    def encoded_pixel_frame_bytes(self, frame_index: int, /) -> bytes: ...
    def encoded_pixel_frame_view(self, frame_index: int, /) -> memoryview: ...
    def set_encoded_pixel_frame(self, frame_index: int, source: object, /) -> None: ...
    def add_encoded_pixel_frame(self, source: object, /) -> None: ...

    def to_array(self, frame: int = ..., decode_mct: bool = ..., *, worker_threads: int = ..., codec_threads: int = ..., plan: object | None = ...) -> object: ...

    def to_array_view(self, frame: int = ...) -> object: ...

    def decode_into(self, out: object, frame: int = ..., decode_mct: bool = ..., *, worker_threads: int = ..., codec_threads: int = ..., plan: object | None = ...) -> object: ...

    def pixel_array(self, frame: int = ..., decode_mct: bool = ..., *, worker_threads: int = ..., codec_threads: int = ..., plan: object | None = ...) -> object: ...

    def __getitem__(self, key: object) -> DataElement: ...

    def __contains__(self, key: object) -> bool: ...

    def __getattr__(self, name: str) -> object: ...

    def __dir__(self) -> list: ...

    def __repr__(self) -> str: ...

@overload
def create_encoder_context(transfer_syntax: Uid, *, options: object | None = ...) -> EncoderContext: ...

@overload
def create_encoder_context(transfer_syntax: str, *, options: object | None = ...) -> EncoderContext: ...

@overload
def apply_rescale(source: object, slope: float, intercept: float) -> object: ...

@overload
def apply_rescale(source: object, transform: RescaleTransform) -> object: ...

def apply_rescale_frames(source: object, slopes: _Sequence[float], intercepts: _Sequence[float]) -> object: ...

def apply_modality_lut(source: object, lut: ModalityLut) -> object: ...

def apply_palette_lut(source: object, lut: PaletteLut) -> object: ...

def apply_voi_lut(source: object, lut: VoiLut) -> object: ...

@overload
def apply_window(source: object, center: float, width: float, function: VoiLutFunction = VoiLutFunction.linear) -> object: ...

@overload
def apply_window(source: object, window: WindowTransform) -> object: ...

def read_file(path: object, load_until: Tag | None = ..., keep_on_error: bool | None = ...) -> DicomFile: ...

def read_file_selected(
    path: object,
    selection: DataSetSelectionLike,
    keep_on_error: bool | None = ...,
) -> DicomFile: ...

def is_dicom_file(path: object) -> bool: ...

def read_bytes(data: object, name: str = ..., load_until: Tag | None = ..., keep_on_error: bool | None = ..., copy: bool = ...) -> object: ...

def read_bytes_selected(
    data: object,
    selection: DataSetSelectionLike,
    name: str = ...,
    keep_on_error: bool | None = ...,
    copy: bool = ...,
) -> object: ...

def load_root_elements_reserve_hint() -> int: ...

def reset_root_elements_reserve_hint() -> None: ...

def set_htj2k_decoder_backend(backend: str) -> None: ...

def get_htj2k_decoder_backend() -> str: ...

def use_openjph_for_htj2k_decoding() -> None: ...

def use_openjpeg_for_htj2k_decoding() -> None: ...

def register_external_codec_plugin(library_path: object) -> None: ...

def clear_external_codec_plugins() -> None: ...

class Tag:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, group: int, element: int) -> None: ...

    @overload
    def __init__(self, keyword: str) -> None: ...

    @staticmethod
    def from_value(value: int) -> Tag: ...

    @property
    def group(self) -> int: ...

    @property
    def element(self) -> int: ...

    @property
    def value(self) -> int: ...

    def is_private(self) -> bool: ...

    def __int__(self) -> int: ...

    def __bool__(self) -> bool: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, arg: Tag, /) -> bool: ...

class Uid:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, text: str) -> None: ...

    @staticmethod
    def lookup(text: str) -> object: ...

    @staticmethod
    def from_value(value: str) -> Uid: ...

    @staticmethod
    def from_keyword(keyword: str) -> Uid: ...

    @property
    def value(self) -> str: ...

    @property
    def keyword(self) -> object: ...

    @property
    def name(self) -> str: ...

    @property
    def type(self) -> str: ...

    @property
    def raw_index(self) -> int: ...

    @property
    def is_valid(self) -> bool: ...

    def __bool__(self) -> bool: ...

    def __repr__(self) -> str: ...

    def __eq__(self, arg: Uid, /) -> bool: ...

class VR:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, value: int) -> None: ...

    @staticmethod
    def from_string(value: str) -> VR: ...

    @staticmethod
    def from_chars(first: str, second: str) -> VR: ...

    @property
    def value(self) -> int: ...

    @property
    def is_known(self) -> bool: ...

    def is_string(self) -> bool: ...

    def is_binary(self) -> bool: ...

    def is_sequence(self) -> bool: ...

    def is_pixel_sequence(self) -> bool: ...

    def uses_specific_character_set(self) -> bool: ...

    def allows_multiple_text_values(self) -> bool: ...

    def padding_byte(self) -> int: ...

    def uses_explicit_16bit_vl(self) -> bool: ...

    def fixed_length(self) -> int: ...

    def str(self) -> str: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, arg: VR, /) -> bool: ...

    None: dicomsdl._dicomsdl.VR = ...

    AE: dicomsdl._dicomsdl.VR = ...

    AS: dicomsdl._dicomsdl.VR = ...

    AT: dicomsdl._dicomsdl.VR = ...

    CS: dicomsdl._dicomsdl.VR = ...

    DA: dicomsdl._dicomsdl.VR = ...

    DS: dicomsdl._dicomsdl.VR = ...

    DT: dicomsdl._dicomsdl.VR = ...

    FD: dicomsdl._dicomsdl.VR = ...

    FL: dicomsdl._dicomsdl.VR = ...

    IS: dicomsdl._dicomsdl.VR = ...

    LO: dicomsdl._dicomsdl.VR = ...

    LT: dicomsdl._dicomsdl.VR = ...

    OB: dicomsdl._dicomsdl.VR = ...

    OD: dicomsdl._dicomsdl.VR = ...

    OF: dicomsdl._dicomsdl.VR = ...

    OV: dicomsdl._dicomsdl.VR = ...

    OL: dicomsdl._dicomsdl.VR = ...

    OW: dicomsdl._dicomsdl.VR = ...

    PN: dicomsdl._dicomsdl.VR = ...

    SH: dicomsdl._dicomsdl.VR = ...

    SL: dicomsdl._dicomsdl.VR = ...

    SQ: dicomsdl._dicomsdl.VR = ...

    SS: dicomsdl._dicomsdl.VR = ...

    ST: dicomsdl._dicomsdl.VR = ...

    SV: dicomsdl._dicomsdl.VR = ...

    TM: dicomsdl._dicomsdl.VR = ...

    UC: dicomsdl._dicomsdl.VR = ...

    UI: dicomsdl._dicomsdl.VR = ...

    UL: dicomsdl._dicomsdl.VR = ...

    UN: dicomsdl._dicomsdl.VR = ...

    UR: dicomsdl._dicomsdl.VR = ...

    US: dicomsdl._dicomsdl.VR = ...

    UT: dicomsdl._dicomsdl.VR = ...

    UV: dicomsdl._dicomsdl.VR = ...

    PX: dicomsdl._dicomsdl.VR = ...

class PixelFragment:
    @property
    def offset(self) -> int: ...

    @property
    def length(self) -> int: ...

    def __repr__(self) -> str: ...

class PixelFrame:
    @property
    def encoded_size(self) -> int: ...

    @property
    def fragments(self) -> list[PixelFragment]: ...

    def encoded_bytes(self) -> bytes: ...

    def encoded_memoryview(self) -> object: ...

class PixelSequence:
    @property
    def number_of_frames(self) -> int: ...

    @property
    def basic_offset_table_offset(self) -> int: ...

    @property
    def basic_offset_table_count(self) -> int: ...

    def __len__(self) -> int: ...

    def frame(self, index: int) -> PixelFrame: ...

    def frame_encoded_bytes(self, index: int) -> bytes: ...

    def frame_encoded_memoryview(self, index: int) -> object: ...

    def __repr__(self) -> str: ...

def keyword_to_tag_vr(keyword: str) -> object: ...

@overload
def tag_to_keyword(tag: Tag) -> object: ...

@overload
def tag_to_keyword(tag_value: int) -> object: ...

@overload
def tag_to_entry(tag: Tag) -> object: ...

@overload
def tag_to_entry(tag_value: int) -> object: ...

def lookup_uid(text: str) -> object: ...

def uid_from_value(value: str) -> Uid: ...

def uid_from_keyword(keyword: str) -> Uid: ...

def transfer_syntax_uids() -> list: ...

def transfer_syntax_uids_encode_supported() -> list: ...

def uid_prefix() -> str: ...

def implementation_class_uid() -> str: ...

def implementation_version_name() -> str: ...

def is_valid_uid_text_strict(text: str) -> bool: ...

def make_uid_with_suffix(suffix: int, root: str | None = ...) -> object: ...

def try_append_uid(base_uid: str, component: int) -> object: ...

def append_uid(base_uid: str, component: int) -> str: ...

def try_generate_uid() -> object: ...

def generate_uid() -> str: ...

def generate_sop_instance_uid() -> str: ...

def generate_series_instance_uid() -> str: ...

def generate_study_instance_uid() -> str: ...

__all__: tuple = ('LogLevel', 'Reporter', 'StderrReporter', 'FileReporter', 'BufferingReporter', 'DICOM_STANDARD_VERSION', 'DICOMSDL_VERSION', '__version__', 'UID_PREFIX', 'IMPLEMENTATION_CLASS_UID', 'IMPLEMENTATION_VERSION_NAME', 'log_info', 'log_warn', 'log_error', 'set_default_reporter', 'set_thread_reporter', 'set_log_level', 'Planar', 'DecodeOptions', 'DecodePlan', 'VoiLutFunction', 'PixelPresentation', 'WindowTransform', 'RescaleTransform', 'ModalityLut', 'VoiLut', 'PaletteLut', 'SupplementalPaletteInfo', 'EnhancedPaletteDataPathAssignmentInfo', 'EnhancedBlendingLutInfo', 'EnhancedPaletteItemInfo', 'EnhancedPaletteInfo', 'EncoderContext', 'create_encoder_context', 'apply_rescale', 'apply_rescale_frames', 'apply_window', 'apply_modality_lut', 'apply_voi_lut', 'apply_palette_lut', 'DicomFile', 'DataElement', 'DataSet', 'DataSetSelection', 'PersonName', 'PersonNameGroup', 'Tag', 'VR', 'Uid', 'read_file', 'read_file_selected', 'is_dicom_file', 'read_bytes', 'read_bytes_selected', 'load_root_elements_reserve_hint', 'reset_root_elements_reserve_hint', 'set_htj2k_decoder_backend', 'get_htj2k_decoder_backend', 'use_openjph_for_htj2k_decoding', 'use_openjpeg_for_htj2k_decoding', 'register_external_codec_plugin', 'clear_external_codec_plugins', 'keyword_to_tag_vr', 'tag_to_keyword', 'tag_to_entry', 'lookup_uid', 'uid_from_value', 'uid_from_keyword', 'transfer_syntax_uids', 'transfer_syntax_uids_encode_supported', 'uid_prefix', 'implementation_class_uid', 'implementation_version_name', 'is_valid_uid_text_strict', 'make_uid_with_suffix', 'try_append_uid', 'append_uid', 'try_generate_uid', 'generate_uid', 'generate_sop_instance_uid', 'generate_series_instance_uid', 'generate_study_instance_uid')
