from collections.abc import Callable
import enum
from typing import overload

from dicomsdl._image import _dicomfile_to_pil_image as to_pil_image


DICOM_STANDARD_VERSION: str = ...

DICOMSDL_VERSION: str = ...

UID_PREFIX: str = ...

IMPLEMENTATION_CLASS_UID: str = ...

IMPLEMENTATION_VERSION_NAME: str = ...

def log_info(arg: str, /) -> None: ...

def log_warn(arg: str, /) -> None: ...

def log_error(arg: str, /) -> None: ...

class LogLevel(enum.Enum):
    Info = 0

    Warning = 1

    Error = 2

class Reporter:
    pass

class StderrReporter(Reporter):
    def __init__(self) -> None: ...

class FileReporter(Reporter):
    def __init__(self, path: str) -> None: ...

class BufferingReporter(Reporter):
    def __init__(self, max_messages: int = ...) -> None: ...

    def take_messages(self, include_level: bool = ...) -> list[str]: ...

    def for_each(self, fn: Callable) -> None: ...

def set_default_reporter(reporter: Reporter | None) -> None: ...

def set_thread_reporter(reporter: Reporter | None) -> None: ...

def set_log_level(level: LogLevel) -> None: ...

class DataElement:
    @property
    def tag(self) -> Tag: ...

    @property
    def vr(self) -> VR: ...

    @property
    def length(self) -> int: ...

    @property
    def offset(self) -> int: ...

    @property
    def vm(self) -> int: ...

    def __bool__(self) -> bool: ...

    def is_present(self) -> bool: ...

    def is_missing(self) -> bool: ...

    @property
    def is_sequence(self) -> bool: ...

    @property
    def is_pixel_sequence(self) -> bool: ...

    @property
    def sequence(self) -> Sequence: ...

    @property
    def pixel_sequence(self) -> PixelSequence: ...

    def to_uid_string(self) -> object: ...

    def to_string_view(self) -> object: ...

    def to_string_views(self) -> object: ...

    def to_utf8_view(self) -> object: ...

    def to_utf8_views(self) -> object: ...

    def to_transfer_syntax_uid(self) -> object: ...

    def to_tag(self, default: object | None = ...) -> object: ...

    def to_tag_vector(self) -> object: ...

    def to_int(self, default: object | None = ...) -> object: ...

    def to_long(self, default: object | None = ...) -> object: ...

    def to_longlong(self, default: object | None = ...) -> object: ...

    def to_double(self, default: object | None = ...) -> object: ...

    def to_int_vector(self, default: object | None = ...) -> object: ...

    def as_uint16_vector(self, default: object | None = ...) -> object: ...

    def as_uint8_vector(self, default: object | None = ...) -> object: ...

    def to_long_vector(self, default: object | None = ...) -> object: ...

    def to_longlong_vector(self, default: object | None = ...) -> object: ...

    def to_double_vector(self, default: object | None = ...) -> object: ...

    def get_value(self) -> object: ...

    def value_span(self) -> object: ...

    def __repr__(self) -> str: ...

class SequenceIterator:
    def __iter__(self) -> SequenceIterator: ...

    def __next__(self) -> DataSet: ...

class Sequence:
    def __len__(self) -> int: ...

    def __getitem__(self, index: int) -> DataSet: ...

    def __iter__(self) -> SequenceIterator: ...

    def add_dataset(self) -> DataSet: ...

    def __repr__(self) -> str: ...

class DataElementIterator:
    def __iter__(self) -> DataElementIterator: ...

    def __next__(self) -> DataElement: ...

class DataSet:
    def __init__(self) -> None: ...

    @property
    def path(self) -> str: ...

    def size(self) -> int: ...

    def add_dataelement(self, tag: Tag, vr: VR | None = ..., offset: int = ..., length: int = ...) -> DataElement: ...

    def remove_dataelement(self, tag: Tag) -> None: ...

    def dump_elements(self) -> None: ...

    def dump(self, max_print_chars: int = ..., include_offset: bool = ...) -> str: ...

    @overload
    def get_dataelement(self, tag: Tag) -> DataElement: ...

    @overload
    def get_dataelement(self, packed_tag: int) -> DataElement: ...

    @overload
    def get_dataelement(self, tag_str: str) -> DataElement: ...

    def __getitem__(self, key: object) -> object: ...

    def __getattr__(self, name: str) -> object: ...

    def __dir__(self) -> list: ...

    def __iter__(self) -> DataElementIterator: ...

class DicomFile:
    @property
    def path(self) -> str: ...

    @property
    def has_error(self) -> bool: ...

    @property
    def error_message(self) -> object: ...

    @property
    def dataset(self) -> DataSet: ...

    def __len__(self) -> int: ...

    def dump(self, max_print_chars: int = ..., include_offset: bool = ...) -> str: ...

    def rebuild_file_meta(self) -> None: ...

    def write_file(self, path: str, *, include_preamble: bool = ..., write_file_meta: bool = ..., keep_existing_meta: bool = ...) -> None: ...

    def write_bytes(self, *, include_preamble: bool = ..., write_file_meta: bool = ..., keep_existing_meta: bool = ...) -> bytes: ...

    def __iter__(self) -> DataElementIterator: ...

    def pixel_data(self, frame_index: int = ...) -> bytes: ...

    def to_array(self, frame: int = ..., scaled: bool = ..., htj2k_decoder: str = ...) -> object: ...

    def to_array_view(self, frame: int = ...) -> object: ...

    def decode_into(self, out: object, frame: int = ..., scaled: bool = ..., threads: int = ..., htj2k_decoder: str = ...) -> object: ...

    def pixel_array(self, frame: int = ..., scaled: bool = ..., htj2k_decoder: str = ...) -> object: ...

    def __getitem__(self, key: object) -> object: ...

    def __getattr__(self, name: str) -> object: ...

    def __dir__(self) -> list: ...

    def __repr__(self) -> str: ...

def read_file(path: str, load_until: Tag | None = ..., keep_on_error: bool | None = ...) -> DicomFile: ...

def read_bytes(data: object, name: str = ..., load_until: Tag | None = ..., keep_on_error: bool | None = ..., copy: bool = ...) -> object: ...

def load_root_elements_reserve_hint() -> int: ...

def reset_root_elements_reserve_hint() -> None: ...

class Tag:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, group: int, element: int) -> None: ...

    @overload
    def __init__(self, keyword: str) -> None: ...

    @staticmethod
    def from_value(value: int) -> Tag: ...

    @property
    def group(self) -> int: ...

    @property
    def element(self) -> int: ...

    @property
    def value(self) -> int: ...

    def is_private(self) -> bool: ...

    def __int__(self) -> int: ...

    def __bool__(self) -> bool: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, arg: Tag, /) -> bool: ...

class Uid:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, text: str) -> None: ...

    @staticmethod
    def lookup(text: str) -> object: ...

    @staticmethod
    def from_value(value: str) -> Uid: ...

    @staticmethod
    def from_keyword(keyword: str) -> Uid: ...

    @property
    def value(self) -> str: ...

    @property
    def keyword(self) -> object: ...

    @property
    def name(self) -> str: ...

    @property
    def type(self) -> str: ...

    @property
    def raw_index(self) -> int: ...

    @property
    def is_valid(self) -> bool: ...

    def __bool__(self) -> bool: ...

    def __repr__(self) -> str: ...

    def __eq__(self, arg: Uid, /) -> bool: ...

class VR:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, value: int) -> None: ...

    @staticmethod
    def from_string(value: str) -> VR: ...

    @staticmethod
    def from_chars(first: str, second: str) -> VR: ...

    @property
    def value(self) -> int: ...

    @property
    def is_known(self) -> bool: ...

    def is_string(self) -> bool: ...

    def is_binary(self) -> bool: ...

    def is_sequence(self) -> bool: ...

    def is_pixel_sequence(self) -> bool: ...

    def padding_byte(self) -> int: ...

    def uses_explicit_16bit_vl(self) -> bool: ...

    def fixed_length(self) -> int: ...

    def str(self) -> str: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, arg: VR, /) -> bool: ...

    None: dicomsdl._dicomsdl.VR = ...

    AE: dicomsdl._dicomsdl.VR = ...

    AS: dicomsdl._dicomsdl.VR = ...

    AT: dicomsdl._dicomsdl.VR = ...

    CS: dicomsdl._dicomsdl.VR = ...

    DA: dicomsdl._dicomsdl.VR = ...

    DS: dicomsdl._dicomsdl.VR = ...

    DT: dicomsdl._dicomsdl.VR = ...

    FD: dicomsdl._dicomsdl.VR = ...

    FL: dicomsdl._dicomsdl.VR = ...

    IS: dicomsdl._dicomsdl.VR = ...

    LO: dicomsdl._dicomsdl.VR = ...

    LT: dicomsdl._dicomsdl.VR = ...

    OB: dicomsdl._dicomsdl.VR = ...

    OD: dicomsdl._dicomsdl.VR = ...

    OF: dicomsdl._dicomsdl.VR = ...

    OV: dicomsdl._dicomsdl.VR = ...

    OL: dicomsdl._dicomsdl.VR = ...

    OW: dicomsdl._dicomsdl.VR = ...

    PN: dicomsdl._dicomsdl.VR = ...

    SH: dicomsdl._dicomsdl.VR = ...

    SL: dicomsdl._dicomsdl.VR = ...

    SQ: dicomsdl._dicomsdl.VR = ...

    SS: dicomsdl._dicomsdl.VR = ...

    ST: dicomsdl._dicomsdl.VR = ...

    SV: dicomsdl._dicomsdl.VR = ...

    TM: dicomsdl._dicomsdl.VR = ...

    UC: dicomsdl._dicomsdl.VR = ...

    UI: dicomsdl._dicomsdl.VR = ...

    UL: dicomsdl._dicomsdl.VR = ...

    UN: dicomsdl._dicomsdl.VR = ...

    UR: dicomsdl._dicomsdl.VR = ...

    US: dicomsdl._dicomsdl.VR = ...

    UT: dicomsdl._dicomsdl.VR = ...

    UV: dicomsdl._dicomsdl.VR = ...

    PX: dicomsdl._dicomsdl.VR = ...

class PixelFragment:
    @property
    def offset(self) -> int: ...

    @property
    def length(self) -> int: ...

    def __repr__(self) -> str: ...

class PixelFrame:
    @property
    def encoded_size(self) -> int: ...

    @property
    def fragments(self) -> list[PixelFragment]: ...

    def encoded_bytes(self) -> bytes: ...

    def encoded_memoryview(self) -> object: ...

class PixelSequence:
    @property
    def number_of_frames(self) -> int: ...

    @property
    def basic_offset_table_offset(self) -> int: ...

    @property
    def basic_offset_table_count(self) -> int: ...

    def __len__(self) -> int: ...

    def frame(self, index: int) -> PixelFrame: ...

    def frame_encoded_bytes(self, index: int) -> bytes: ...

    def frame_encoded_memoryview(self, index: int) -> object: ...

    def __repr__(self) -> str: ...

def keyword_to_tag_vr(keyword: str) -> object: ...

@overload
def tag_to_keyword(tag: Tag) -> object: ...

@overload
def tag_to_keyword(tag_value: int) -> object: ...

@overload
def tag_to_entry(tag: Tag) -> object: ...

@overload
def tag_to_entry(tag_value: int) -> object: ...

def lookup_uid(text: str) -> object: ...

def uid_from_value(value: str) -> Uid: ...

def uid_from_keyword(keyword: str) -> Uid: ...

def uid_prefix() -> str: ...

def implementation_class_uid() -> str: ...

def implementation_version_name() -> str: ...

def is_valid_uid_text_strict(text: str) -> bool: ...

def make_uid_with_suffix(suffix: int, root: str | None = ...) -> object: ...

def try_append_uid(base_uid: str, component: int) -> object: ...

def append_uid(base_uid: str, component: int) -> str: ...

def try_generate_uid() -> object: ...

def generate_uid() -> str: ...

def generate_sop_instance_uid() -> str: ...

def generate_series_instance_uid() -> str: ...

def generate_study_instance_uid() -> str: ...

__all__: tuple = ('LogLevel', 'Reporter', 'StderrReporter', 'FileReporter', 'BufferingReporter', 'DICOM_STANDARD_VERSION', 'DICOMSDL_VERSION', '__version__', 'UID_PREFIX', 'IMPLEMENTATION_CLASS_UID', 'IMPLEMENTATION_VERSION_NAME', 'log_info', 'log_warn', 'log_error', 'set_default_reporter', 'set_thread_reporter', 'set_log_level', 'DicomFile', 'DataSet', 'Tag', 'VR', 'Uid', 'read_file', 'read_bytes', 'load_root_elements_reserve_hint', 'reset_root_elements_reserve_hint', 'keyword_to_tag_vr', 'tag_to_keyword', 'tag_to_entry', 'lookup_uid', 'uid_from_value', 'uid_from_keyword', 'uid_prefix', 'implementation_class_uid', 'implementation_version_name', 'is_valid_uid_text_strict', 'make_uid_with_suffix', 'try_append_uid', 'append_uid', 'try_generate_uid', 'generate_uid', 'generate_sop_instance_uid', 'generate_series_instance_uid', 'generate_study_instance_uid')
