#ifndef DICOMSDL_PIXEL_CODEC_PLUGIN_ABI_V2_H
#define DICOMSDL_PIXEL_CODEC_PLUGIN_ABI_V2_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define PIXEL_CODEC_PLUGIN_ABI_V2 0x00020000u

typedef uint32_t pixel_error_code_v2;

#define PIXEL_CODEC_ERR_OK ((pixel_error_code_v2)0u)
#define PIXEL_CODEC_ERR_INVALID_ARGUMENT ((pixel_error_code_v2)1u)
#define PIXEL_CODEC_ERR_UNSUPPORTED ((pixel_error_code_v2)2u)
#define PIXEL_CODEC_ERR_OUTPUT_TOO_SMALL ((pixel_error_code_v2)3u)
#define PIXEL_CODEC_ERR_FAILED ((pixel_error_code_v2)4u)

typedef struct pixel_const_buffer_v2 {
  const uint8_t* data;
  uint64_t size;
} pixel_const_buffer_v2;

typedef struct pixel_output_buffer_v2 {
  uint8_t* data;
  uint64_t size;
} pixel_output_buffer_v2;

typedef struct pixel_option_kv_v2 {
  const char* key;
  const char* value;
} pixel_option_kv_v2;

typedef struct pixel_option_list_v2 {
  const pixel_option_kv_v2* items;
  uint32_t count;
} pixel_option_list_v2;

typedef enum pixel_planar_code_v2 {
  PIXEL_PLANAR_INTERLEAVED_V2 = 0,
  PIXEL_PLANAR_PLANAR_V2 = 1
} pixel_planar_code_v2;

typedef enum pixel_dtype_code_v2 {
  PIXEL_DTYPE_UNKNOWN_V2 = 0,
  PIXEL_DTYPE_U8_V2 = 1,
  PIXEL_DTYPE_S8_V2 = 2,
  PIXEL_DTYPE_U16_V2 = 3,
  PIXEL_DTYPE_S16_V2 = 4,
  PIXEL_DTYPE_U32_V2 = 5,
  PIXEL_DTYPE_S32_V2 = 6,
  PIXEL_DTYPE_F32_V2 = 7,
  PIXEL_DTYPE_F64_V2 = 8
} pixel_dtype_code_v2;

typedef enum pixel_codec_profile_code_v2 {
  PIXEL_CODEC_PROFILE_UNKNOWN_V2 = 0,
  PIXEL_CODEC_PROFILE_NATIVE_UNCOMPRESSED_V2 = 1,
  PIXEL_CODEC_PROFILE_ENCAPSULATED_UNCOMPRESSED_V2 = 2,
  PIXEL_CODEC_PROFILE_RLE_LOSSLESS_V2 = 3,
  PIXEL_CODEC_PROFILE_JPEG_LOSSLESS_V2 = 4,
  PIXEL_CODEC_PROFILE_JPEG_LOSSY_V2 = 5,
  PIXEL_CODEC_PROFILE_JPEGLS_LOSSLESS_V2 = 6,
  PIXEL_CODEC_PROFILE_JPEGLS_NEAR_LOSSLESS_V2 = 7,
  PIXEL_CODEC_PROFILE_JPEG2000_LOSSLESS_V2 = 8,
  PIXEL_CODEC_PROFILE_JPEG2000_LOSSY_V2 = 9,
  PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_V2 = 10,
  PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_RPCL_V2 = 11,
  PIXEL_CODEC_PROFILE_HTJ2K_LOSSY_V2 = 12,
  PIXEL_CODEC_PROFILE_JPEGXL_LOSSLESS_V2 = 13,
  PIXEL_CODEC_PROFILE_JPEGXL_LOSSY_V2 = 14,
  PIXEL_CODEC_PROFILE_JPEGXL_JPEG_RECOMPRESSION_V2 = 15
} pixel_codec_profile_code_v2;

typedef uint64_t pixel_supported_profile_flags_v2;

#define PIXEL_CODEC_PROFILE_DEC_FLAG_V2(profile_code) \
  (UINT64_C(1) << (profile_code))
#define PIXEL_CODEC_PROFILE_ENC_FLAG_V2(profile_code) \
  (UINT64_C(1) << (32u + (profile_code)))

#define PIXEL_CODEC_PROFILE_NATIVE_UNCOMPRESSED_DEC_V2 \
  PIXEL_CODEC_PROFILE_DEC_FLAG_V2(PIXEL_CODEC_PROFILE_NATIVE_UNCOMPRESSED_V2)
#define PIXEL_CODEC_PROFILE_NATIVE_UNCOMPRESSED_ENC_V2 \
  PIXEL_CODEC_PROFILE_ENC_FLAG_V2(PIXEL_CODEC_PROFILE_NATIVE_UNCOMPRESSED_V2)

#define PIXEL_CODEC_PROFILE_ENCAPSULATED_UNCOMPRESSED_DEC_V2 \
  PIXEL_CODEC_PROFILE_DEC_FLAG_V2(PIXEL_CODEC_PROFILE_ENCAPSULATED_UNCOMPRESSED_V2)
#define PIXEL_CODEC_PROFILE_ENCAPSULATED_UNCOMPRESSED_ENC_V2 \
  PIXEL_CODEC_PROFILE_ENC_FLAG_V2(PIXEL_CODEC_PROFILE_ENCAPSULATED_UNCOMPRESSED_V2)

#define PIXEL_CODEC_PROFILE_RLE_LOSSLESS_DEC_V2 \
  PIXEL_CODEC_PROFILE_DEC_FLAG_V2(PIXEL_CODEC_PROFILE_RLE_LOSSLESS_V2)
#define PIXEL_CODEC_PROFILE_RLE_LOSSLESS_ENC_V2 \
  PIXEL_CODEC_PROFILE_ENC_FLAG_V2(PIXEL_CODEC_PROFILE_RLE_LOSSLESS_V2)

#define PIXEL_CODEC_PROFILE_JPEG_LOSSLESS_DEC_V2 \
  PIXEL_CODEC_PROFILE_DEC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEG_LOSSLESS_V2)
#define PIXEL_CODEC_PROFILE_JPEG_LOSSLESS_ENC_V2 \
  PIXEL_CODEC_PROFILE_ENC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEG_LOSSLESS_V2)

#define PIXEL_CODEC_PROFILE_JPEG_LOSSY_DEC_V2 \
  PIXEL_CODEC_PROFILE_DEC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEG_LOSSY_V2)
#define PIXEL_CODEC_PROFILE_JPEG_LOSSY_ENC_V2 \
  PIXEL_CODEC_PROFILE_ENC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEG_LOSSY_V2)

#define PIXEL_CODEC_PROFILE_JPEGLS_LOSSLESS_DEC_V2 \
  PIXEL_CODEC_PROFILE_DEC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEGLS_LOSSLESS_V2)
#define PIXEL_CODEC_PROFILE_JPEGLS_LOSSLESS_ENC_V2 \
  PIXEL_CODEC_PROFILE_ENC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEGLS_LOSSLESS_V2)

#define PIXEL_CODEC_PROFILE_JPEGLS_NEAR_LOSSLESS_DEC_V2 \
  PIXEL_CODEC_PROFILE_DEC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEGLS_NEAR_LOSSLESS_V2)
#define PIXEL_CODEC_PROFILE_JPEGLS_NEAR_LOSSLESS_ENC_V2 \
  PIXEL_CODEC_PROFILE_ENC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEGLS_NEAR_LOSSLESS_V2)

#define PIXEL_CODEC_PROFILE_JPEG2000_LOSSLESS_DEC_V2 \
  PIXEL_CODEC_PROFILE_DEC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEG2000_LOSSLESS_V2)
#define PIXEL_CODEC_PROFILE_JPEG2000_LOSSLESS_ENC_V2 \
  PIXEL_CODEC_PROFILE_ENC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEG2000_LOSSLESS_V2)

#define PIXEL_CODEC_PROFILE_JPEG2000_LOSSY_DEC_V2 \
  PIXEL_CODEC_PROFILE_DEC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEG2000_LOSSY_V2)
#define PIXEL_CODEC_PROFILE_JPEG2000_LOSSY_ENC_V2 \
  PIXEL_CODEC_PROFILE_ENC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEG2000_LOSSY_V2)

#define PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_DEC_V2 \
  PIXEL_CODEC_PROFILE_DEC_FLAG_V2(PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_V2)
#define PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_ENC_V2 \
  PIXEL_CODEC_PROFILE_ENC_FLAG_V2(PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_V2)

#define PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_RPCL_DEC_V2 \
  PIXEL_CODEC_PROFILE_DEC_FLAG_V2(PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_RPCL_V2)
#define PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_RPCL_ENC_V2 \
  PIXEL_CODEC_PROFILE_ENC_FLAG_V2(PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_RPCL_V2)

#define PIXEL_CODEC_PROFILE_HTJ2K_LOSSY_DEC_V2 \
  PIXEL_CODEC_PROFILE_DEC_FLAG_V2(PIXEL_CODEC_PROFILE_HTJ2K_LOSSY_V2)
#define PIXEL_CODEC_PROFILE_HTJ2K_LOSSY_ENC_V2 \
  PIXEL_CODEC_PROFILE_ENC_FLAG_V2(PIXEL_CODEC_PROFILE_HTJ2K_LOSSY_V2)

#define PIXEL_CODEC_PROFILE_JPEGXL_LOSSLESS_DEC_V2 \
  PIXEL_CODEC_PROFILE_DEC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEGXL_LOSSLESS_V2)
#define PIXEL_CODEC_PROFILE_JPEGXL_LOSSLESS_ENC_V2 \
  PIXEL_CODEC_PROFILE_ENC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEGXL_LOSSLESS_V2)

#define PIXEL_CODEC_PROFILE_JPEGXL_LOSSY_DEC_V2 \
  PIXEL_CODEC_PROFILE_DEC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEGXL_LOSSY_V2)
#define PIXEL_CODEC_PROFILE_JPEGXL_LOSSY_ENC_V2 \
  PIXEL_CODEC_PROFILE_ENC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEGXL_LOSSY_V2)

#define PIXEL_CODEC_PROFILE_JPEGXL_JPEG_RECOMPRESSION_DEC_V2 \
  PIXEL_CODEC_PROFILE_DEC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEGXL_JPEG_RECOMPRESSION_V2)
#define PIXEL_CODEC_PROFILE_JPEGXL_JPEG_RECOMPRESSION_ENC_V2 \
  PIXEL_CODEC_PROFILE_ENC_FLAG_V2(PIXEL_CODEC_PROFILE_JPEGXL_JPEG_RECOMPRESSION_V2)

typedef uint32_t (*pixel_copy_last_error_detail_fn_v2)(
    const void* ctx, char* out_detail, uint32_t out_detail_capacity);

#ifdef __cplusplus
}
#endif

#endif  // DICOMSDL_PIXEL_CODEC_PLUGIN_ABI_V2_H
