#ifndef DICOMSDL_PIXEL_CODEC_PLUGIN_ABI_H
#define DICOMSDL_PIXEL_CODEC_PLUGIN_ABI_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define PIXEL_CODEC_PLUGIN_ABI 0x00030000u

typedef uint32_t pixel_error_code;

#define PIXEL_CODEC_ERR_OK ((pixel_error_code)0u)
#define PIXEL_CODEC_ERR_INVALID_ARGUMENT ((pixel_error_code)1u)
#define PIXEL_CODEC_ERR_UNSUPPORTED ((pixel_error_code)2u)
#define PIXEL_CODEC_ERR_OUTPUT_TOO_SMALL ((pixel_error_code)3u)
#define PIXEL_CODEC_ERR_FAILED ((pixel_error_code)4u)

typedef struct pixel_const_buffer {
  const uint8_t* data;
  uint64_t size;
} pixel_const_buffer;

typedef struct pixel_output_buffer {
  uint8_t* data;
  uint64_t size;
} pixel_output_buffer;

typedef struct pixel_option_kv {
  const char* key;
  const char* value;
} pixel_option_kv;

typedef struct pixel_option_list {
  const pixel_option_kv* items;
  uint32_t count;
} pixel_option_list;

typedef enum pixel_planar_code {
  PIXEL_PLANAR_INTERLEAVED = 0,
  PIXEL_PLANAR_PLANAR = 1
} pixel_planar_code;

typedef enum pixel_dtype_code {
  PIXEL_DTYPE_UNKNOWN = 0,
  PIXEL_DTYPE_U8 = 1,
  PIXEL_DTYPE_S8 = 2,
  PIXEL_DTYPE_U16 = 3,
  PIXEL_DTYPE_S16 = 4,
  PIXEL_DTYPE_U32 = 5,
  PIXEL_DTYPE_S32 = 6,
  PIXEL_DTYPE_F32 = 7,
  PIXEL_DTYPE_F64 = 8
} pixel_dtype_code;

typedef enum pixel_codec_profile_code {
  PIXEL_CODEC_PROFILE_UNKNOWN = 0,
  PIXEL_CODEC_PROFILE_NATIVE_UNCOMPRESSED = 1,
  PIXEL_CODEC_PROFILE_ENCAPSULATED_UNCOMPRESSED = 2,
  PIXEL_CODEC_PROFILE_RLE_LOSSLESS = 3,
  PIXEL_CODEC_PROFILE_JPEG_LOSSLESS = 4,
  PIXEL_CODEC_PROFILE_JPEG_LOSSY = 5,
  PIXEL_CODEC_PROFILE_JPEGLS_LOSSLESS = 6,
  PIXEL_CODEC_PROFILE_JPEGLS_NEAR_LOSSLESS = 7,
  PIXEL_CODEC_PROFILE_JPEG2000_LOSSLESS = 8,
  PIXEL_CODEC_PROFILE_JPEG2000_LOSSY = 9,
  PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS = 10,
  PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_RPCL = 11,
  PIXEL_CODEC_PROFILE_HTJ2K_LOSSY = 12,
  PIXEL_CODEC_PROFILE_JPEGXL_LOSSLESS = 13,
  PIXEL_CODEC_PROFILE_JPEGXL_LOSSY = 14,
  PIXEL_CODEC_PROFILE_JPEGXL_JPEG_RECOMPRESSION = 15
} pixel_codec_profile_code;

typedef uint64_t pixel_supported_profile_flags;

#define PIXEL_CODEC_PROFILE_DEC_FLAG(profile_code) \
  (UINT64_C(1) << (profile_code))
#define PIXEL_CODEC_PROFILE_ENC_FLAG(profile_code) \
  (UINT64_C(1) << (32u + (profile_code)))

#define PIXEL_CODEC_PROFILE_NATIVE_UNCOMPRESSED_DEC \
  PIXEL_CODEC_PROFILE_DEC_FLAG(PIXEL_CODEC_PROFILE_NATIVE_UNCOMPRESSED)
#define PIXEL_CODEC_PROFILE_NATIVE_UNCOMPRESSED_ENC \
  PIXEL_CODEC_PROFILE_ENC_FLAG(PIXEL_CODEC_PROFILE_NATIVE_UNCOMPRESSED)

#define PIXEL_CODEC_PROFILE_ENCAPSULATED_UNCOMPRESSED_DEC \
  PIXEL_CODEC_PROFILE_DEC_FLAG(PIXEL_CODEC_PROFILE_ENCAPSULATED_UNCOMPRESSED)
#define PIXEL_CODEC_PROFILE_ENCAPSULATED_UNCOMPRESSED_ENC \
  PIXEL_CODEC_PROFILE_ENC_FLAG(PIXEL_CODEC_PROFILE_ENCAPSULATED_UNCOMPRESSED)

#define PIXEL_CODEC_PROFILE_RLE_LOSSLESS_DEC \
  PIXEL_CODEC_PROFILE_DEC_FLAG(PIXEL_CODEC_PROFILE_RLE_LOSSLESS)
#define PIXEL_CODEC_PROFILE_RLE_LOSSLESS_ENC \
  PIXEL_CODEC_PROFILE_ENC_FLAG(PIXEL_CODEC_PROFILE_RLE_LOSSLESS)

#define PIXEL_CODEC_PROFILE_JPEG_LOSSLESS_DEC \
  PIXEL_CODEC_PROFILE_DEC_FLAG(PIXEL_CODEC_PROFILE_JPEG_LOSSLESS)
#define PIXEL_CODEC_PROFILE_JPEG_LOSSLESS_ENC \
  PIXEL_CODEC_PROFILE_ENC_FLAG(PIXEL_CODEC_PROFILE_JPEG_LOSSLESS)

#define PIXEL_CODEC_PROFILE_JPEG_LOSSY_DEC \
  PIXEL_CODEC_PROFILE_DEC_FLAG(PIXEL_CODEC_PROFILE_JPEG_LOSSY)
#define PIXEL_CODEC_PROFILE_JPEG_LOSSY_ENC \
  PIXEL_CODEC_PROFILE_ENC_FLAG(PIXEL_CODEC_PROFILE_JPEG_LOSSY)

#define PIXEL_CODEC_PROFILE_JPEGLS_LOSSLESS_DEC \
  PIXEL_CODEC_PROFILE_DEC_FLAG(PIXEL_CODEC_PROFILE_JPEGLS_LOSSLESS)
#define PIXEL_CODEC_PROFILE_JPEGLS_LOSSLESS_ENC \
  PIXEL_CODEC_PROFILE_ENC_FLAG(PIXEL_CODEC_PROFILE_JPEGLS_LOSSLESS)

#define PIXEL_CODEC_PROFILE_JPEGLS_NEAR_LOSSLESS_DEC \
  PIXEL_CODEC_PROFILE_DEC_FLAG(PIXEL_CODEC_PROFILE_JPEGLS_NEAR_LOSSLESS)
#define PIXEL_CODEC_PROFILE_JPEGLS_NEAR_LOSSLESS_ENC \
  PIXEL_CODEC_PROFILE_ENC_FLAG(PIXEL_CODEC_PROFILE_JPEGLS_NEAR_LOSSLESS)

#define PIXEL_CODEC_PROFILE_JPEG2000_LOSSLESS_DEC \
  PIXEL_CODEC_PROFILE_DEC_FLAG(PIXEL_CODEC_PROFILE_JPEG2000_LOSSLESS)
#define PIXEL_CODEC_PROFILE_JPEG2000_LOSSLESS_ENC \
  PIXEL_CODEC_PROFILE_ENC_FLAG(PIXEL_CODEC_PROFILE_JPEG2000_LOSSLESS)

#define PIXEL_CODEC_PROFILE_JPEG2000_LOSSY_DEC \
  PIXEL_CODEC_PROFILE_DEC_FLAG(PIXEL_CODEC_PROFILE_JPEG2000_LOSSY)
#define PIXEL_CODEC_PROFILE_JPEG2000_LOSSY_ENC \
  PIXEL_CODEC_PROFILE_ENC_FLAG(PIXEL_CODEC_PROFILE_JPEG2000_LOSSY)

#define PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_DEC \
  PIXEL_CODEC_PROFILE_DEC_FLAG(PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS)
#define PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_ENC \
  PIXEL_CODEC_PROFILE_ENC_FLAG(PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS)

#define PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_RPCL_DEC \
  PIXEL_CODEC_PROFILE_DEC_FLAG(PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_RPCL)
#define PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_RPCL_ENC \
  PIXEL_CODEC_PROFILE_ENC_FLAG(PIXEL_CODEC_PROFILE_HTJ2K_LOSSLESS_RPCL)

#define PIXEL_CODEC_PROFILE_HTJ2K_LOSSY_DEC \
  PIXEL_CODEC_PROFILE_DEC_FLAG(PIXEL_CODEC_PROFILE_HTJ2K_LOSSY)
#define PIXEL_CODEC_PROFILE_HTJ2K_LOSSY_ENC \
  PIXEL_CODEC_PROFILE_ENC_FLAG(PIXEL_CODEC_PROFILE_HTJ2K_LOSSY)

#define PIXEL_CODEC_PROFILE_JPEGXL_LOSSLESS_DEC \
  PIXEL_CODEC_PROFILE_DEC_FLAG(PIXEL_CODEC_PROFILE_JPEGXL_LOSSLESS)
#define PIXEL_CODEC_PROFILE_JPEGXL_LOSSLESS_ENC \
  PIXEL_CODEC_PROFILE_ENC_FLAG(PIXEL_CODEC_PROFILE_JPEGXL_LOSSLESS)

#define PIXEL_CODEC_PROFILE_JPEGXL_LOSSY_DEC \
  PIXEL_CODEC_PROFILE_DEC_FLAG(PIXEL_CODEC_PROFILE_JPEGXL_LOSSY)
#define PIXEL_CODEC_PROFILE_JPEGXL_LOSSY_ENC \
  PIXEL_CODEC_PROFILE_ENC_FLAG(PIXEL_CODEC_PROFILE_JPEGXL_LOSSY)

#define PIXEL_CODEC_PROFILE_JPEGXL_JPEG_RECOMPRESSION_DEC \
  PIXEL_CODEC_PROFILE_DEC_FLAG(PIXEL_CODEC_PROFILE_JPEGXL_JPEG_RECOMPRESSION)
#define PIXEL_CODEC_PROFILE_JPEGXL_JPEG_RECOMPRESSION_ENC \
  PIXEL_CODEC_PROFILE_ENC_FLAG(PIXEL_CODEC_PROFILE_JPEGXL_JPEG_RECOMPRESSION)

typedef uint32_t (*pixel_copy_last_error_detail_fn)(
    const void* ctx, char* out_detail, uint32_t out_detail_capacity);

#ifdef __cplusplus
}
#endif

#endif  // DICOMSDL_PIXEL_CODEC_PLUGIN_ABI_H
