#!/usr/bin/env python3
from __future__ import annotations

import pathlib
import urllib.request

from _generator_common import write_text_if_changed


ROOT = pathlib.Path(__file__).resolve().parents[2]
DATA_DIR = ROOT / "misc" / "charset" / "data" / "unicode"
OUT_PATH = ROOT / "src" / "charset" / "generated" / "sbcs_to_unicode_selected.hpp"

SOURCES = [
    {
        "defined_term": "ISO_IR 101",
        "description": "Latin alphabet No. 2",
        "filename": "8859-2.TXT",
        "url": "https://www.unicode.org/Public/MAPPINGS/ISO8859/8859-2.TXT",
        "array_name": "map_latin2_to_unicode_g1",
    },
    {
        "defined_term": "ISO_IR 109",
        "description": "Latin alphabet No. 3",
        "filename": "8859-3.TXT",
        "url": "https://www.unicode.org/Public/MAPPINGS/ISO8859/8859-3.TXT",
        "array_name": "map_latin3_to_unicode_g1",
    },
    {
        "defined_term": "ISO_IR 110",
        "description": "Latin alphabet No. 4",
        "filename": "8859-4.TXT",
        "url": "https://www.unicode.org/Public/MAPPINGS/ISO8859/8859-4.TXT",
        "array_name": "map_latin4_to_unicode_g1",
    },
    {
        "defined_term": "ISO_IR 144",
        "description": "Cyrillic",
        "filename": "8859-5.TXT",
        "url": "https://www.unicode.org/Public/MAPPINGS/ISO8859/8859-5.TXT",
        "array_name": "map_cyrillic_to_unicode_g1",
    },
    {
        "defined_term": "ISO_IR 127",
        "description": "Arabic",
        "filename": "8859-6.TXT",
        "url": "https://www.unicode.org/Public/MAPPINGS/ISO8859/8859-6.TXT",
        "array_name": "map_arabic_to_unicode_g1",
    },
    {
        "defined_term": "ISO_IR 126",
        "description": "Greek",
        "filename": "8859-7.TXT",
        "url": "https://www.unicode.org/Public/MAPPINGS/ISO8859/8859-7.TXT",
        "array_name": "map_greek_to_unicode_g1",
    },
    {
        "defined_term": "ISO_IR 138",
        "description": "Hebrew",
        "filename": "8859-8.TXT",
        "url": "https://www.unicode.org/Public/MAPPINGS/ISO8859/8859-8.TXT",
        "array_name": "map_hebrew_to_unicode_g1",
    },
    {
        "defined_term": "ISO_IR 148",
        "description": "Latin alphabet No. 5",
        "filename": "8859-9.TXT",
        "url": "https://www.unicode.org/Public/MAPPINGS/ISO8859/8859-9.TXT",
        "array_name": "map_latin5_to_unicode_g1",
    },
    {
        "defined_term": "ISO_IR 166",
        "description": "Thai",
        "filename": "8859-11.TXT",
        "url": "https://www.unicode.org/Public/MAPPINGS/ISO8859/8859-11.TXT",
        "array_name": "map_thai_to_unicode_g1",
    },
    {
        "defined_term": "ISO_IR 203",
        "description": "Latin alphabet No. 9",
        "filename": "8859-15.TXT",
        "url": "https://www.unicode.org/Public/MAPPINGS/ISO8859/8859-15.TXT",
        "array_name": "map_latin9_to_unicode_g1",
    },
]


def ensure_sources_downloaded() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    for source in SOURCES:
        path = DATA_DIR / source["filename"]
        if path.exists():
            continue
        with urllib.request.urlopen(source["url"]) as response:
            path.write_bytes(response.read())


def parse_unicode_mapping(path: pathlib.Path) -> list[int]:
    mapping = [0xFFFD] * 256
    with path.open("r", encoding="utf-8", errors="replace") as handle:
        for raw_line in handle:
            line = raw_line.split("#", 1)[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            if not parts[0].startswith("0x") or not parts[1].startswith("0x"):
                continue
            byte_value = int(parts[0], 16)
            codepoint = int(parts[1], 16)
            if 0 <= byte_value <= 0xFF:
                mapping[byte_value] = codepoint
    return mapping


def format_array(name: str, values: list[int], comment: str) -> list[str]:
    lines = [
        f"// {comment}",
        f"inline constexpr std::array<std::uint16_t, 128> {name} = {{",
    ]
    for row_start in range(0x80, 0x100, 8):
        row = ", ".join(f"0x{values[index]:x}" for index in range(row_start, row_start + 8))
        lines.append(f"    {row},")
    lines.append("};")
    lines.append("")
    return lines


def generate_header() -> str:
    lines = [
        "#pragma once",
        "",
        "// Auto-generated by misc/charset/generate_selected_sbcs_tables.py",
        "// Source origin:",
    ]
    for source in SOURCES:
        lines.append(
            f"// - {source['url']} -> {source['defined_term']} ({source['description']})"
        )
    lines.extend(
        [
            "#include <array>",
            "#include <cstdint>",
            "",
            "namespace dicom::charset::tables {",
            "",
        ]
    )

    for source in SOURCES:
        mapping = parse_unicode_mapping(DATA_DIR / source["filename"])
        lines.extend(
            format_array(
                source["array_name"],
                mapping,
                f"{source['defined_term']} ({source['description']}) G1 mapping",
            )
        )

    lines.append("}  // namespace dicom::charset::tables")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ensure_sources_downloaded()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    write_text_if_changed(OUT_PATH, generate_header())


if __name__ == "__main__":
    main()
