#!/usr/bin/env python3
from __future__ import annotations

import pathlib
import urllib.request

from _generator_common import write_text_if_changed


ROOT = pathlib.Path(__file__).resolve().parents[2]
DATA_DIR = ROOT / "misc" / "charset" / "data" / "unicode"
OUT_DIR = ROOT / "src" / "charset" / "generated"

SOURCES = [
    {
        "name": "jisx0208",
        "filename": "JIS0208.TXT",
        "url": "https://www.unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/JIS0208.TXT",
        "output": "jisx0208_tables.hpp",
        "col_mb": 1,
        "col_uc": 2,
    },
    {
        "name": "jisx0212",
        "filename": "JIS0212.TXT",
        "url": "https://www.unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/JIS0212.TXT",
        "output": "jisx0212_tables.hpp",
        "col_mb": 0,
        "col_uc": 1,
    },
]


def ensure_source_downloaded(filename: str, url: str) -> pathlib.Path:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    path = DATA_DIR / filename
    if not path.exists():
        with urllib.request.urlopen(url) as response:
            path.write_bytes(response.read())
    return path


def parse_mapping(path: pathlib.Path, col_mb: int, col_uc: int) -> tuple[dict[int, int], dict[int, int]]:
    multibyte_to_unicode: dict[int, int] = {}
    unicode_to_multibyte: dict[int, int] = {}
    with path.open("r", encoding="latin1") as handle:
        for raw_line in handle:
            line = raw_line.split("#", 1)[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) <= max(col_mb, col_uc):
                continue
            if not parts[col_mb].startswith("0x") or not parts[col_uc].startswith("0x"):
                continue
            multibyte = int(parts[col_mb], 16)
            codepoint = int(parts[col_uc], 16)
            multibyte_to_unicode[multibyte] = codepoint
            unicode_to_multibyte[codepoint] = multibyte
    return multibyte_to_unicode, unicode_to_multibyte


def format_uint16_array(name: str, values: list[int], comment: str) -> list[str]:
    lines = [f"// {comment}", f"inline constexpr std::uint16_t {name}[{len(values)}] = {{"]
    row: list[str] = []
    for index, value in enumerate(values):
        row.append(f"0x{value:04x}")
        if len(row) == 8 or index + 1 == len(values):
            suffix = "," if index + 1 != len(values) else ""
            lines.append("    " + ", ".join(row) + suffix)
            row = []
    lines.append("};")
    lines.append("")
    return lines


def build_unicode_to_index(unicode_to_multibyte: dict[int, int]) -> list[int]:
    page_counts = [0] * 256
    for codepoint in unicode_to_multibyte:
        page_counts[(codepoint >> 8) & 0xFF] += 1

    page_exists = [1 if count else 0 for count in page_counts]
    values: list[int] = []
    for page in range(256):
        offset = sum(page_exists[:page]) * 32 + 256
        values.append(offset if page_exists[page] else 0)

    index = 0
    for page in range(256):
        if not page_exists[page]:
            continue
        for nibble in range(16):
            start = (page << 8) + (nibble << 4)
            end = start + 16
            usebit = 0
            values.append(index)
            for codepoint in range(start, end):
                usebit <<= 1
                if codepoint in unicode_to_multibyte:
                    usebit |= 1
                    index += 1
            values.append(usebit)
    return values


def build_index_to_multibyte(unicode_to_multibyte: dict[int, int]) -> list[int]:
    return [unicode_to_multibyte[codepoint] for codepoint in sorted(unicode_to_multibyte)]


def build_multibyte_to_unicode(multibyte_to_unicode: dict[int, int]) -> list[int]:
    values: list[int] = []
    pages = {multibyte >> 8 for multibyte in multibyte_to_unicode}
    offset = 188
    for page in range(0x21, 0x7F):
        if page in pages:
            values.append(offset)
            offset += 94
        else:
            values.append(94)

    values.extend([0] * 94)
    for page in range(0x21, 0x7F):
        if page not in pages:
            continue
        for low in range(0x21, 0x7F):
            values.append(multibyte_to_unicode.get((page << 8) | low, 0))
    return values


def generate_header(config: dict[str, object]) -> str:
    source_path = ensure_source_downloaded(str(config["filename"]), str(config["url"]))
    multibyte_to_unicode, unicode_to_multibyte = parse_mapping(
        source_path, int(config["col_mb"]), int(config["col_uc"])
    )
    name = str(config["name"])

    lines = [
        "#pragma once",
        "",
        "// Auto-generated by misc/charset/generate_jis_tables.py",
        "// Source origin:",
        f"// - {config['url']}",
        "#include <cstdint>",
        "",
        "namespace dicom::charset::tables {",
        "",
    ]

    lines.extend(
        format_uint16_array(
            f"map_{name}_unicode_to_index",
            build_unicode_to_index(unicode_to_multibyte),
            f"Unicode to {name.upper()} lookup index",
        )
    )
    lines.extend(
        format_uint16_array(
            f"map_{name}_index_to_multibyte",
            build_index_to_multibyte(unicode_to_multibyte),
            f"Lookup index to {name.upper()} multibyte value",
        )
    )
    lines.extend(
        format_uint16_array(
            f"map_{name}_multibyte_to_unicode",
            build_multibyte_to_unicode(multibyte_to_unicode),
            f"{name.upper()} multibyte value to Unicode",
        )
    )
    lines.append("}  // namespace dicom::charset::tables")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for config in SOURCES:
        out_path = OUT_DIR / str(config["output"])
        write_text_if_changed(out_path, generate_header(config))


if __name__ == "__main__":
    main()
